name: rajlaxmi_myhub_app
description: "Rajlaxmi MyHub â€” Smart Device and SIM Manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  permission_handler: ^12.0.1
  mobile_number: ^3.0.0
  call_log: ^6.0.1
  image_picker: ^1.0.4
  flutter_contacts: ^1.1.7
  phone_state: ^3.0.0
  flutter_phone_direct_caller: ^2.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.0
  flutter_sound: ^9.28.0
  record: ^6.1.2
  path_provider: ^2.0.15
  share_plus: ^12.0.0
  audioplayers: ^6.5.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/Callifo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/Callifo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/